# Generated by Django 6.0.1 on 2026-02-03 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('total_driving_hours', models.DurationField()),
                ('total_on_duty_hour', models.DurationField()),
                ('total_off_duty_hour', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(max_length=255)),
                ('cycle_used_hours', models.FloatField()),
                ('total_distance_miles', models.FloatField()),
                ('total_duration_hours', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty')], max_length=10)),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_segments', to='trip.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DRIVING', 'Driving'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('REST', 'Rest'), ('FUEL', 'Fuel'), ('BREAK', 'Break')], max_length=10)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('day_number', models.IntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='trip.trip')),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trip.trip'),
        ),
    ]
