# Generated by Django 6.0.1 on 2026-01-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_stops', to='trip.trip')),
            ],
        ),
    ]
