# Generated by Django 6.0.1 on 2026-02-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='total_distance_miles',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_duration_hours',
            field=models.FloatField(blank=True),
        ),
    ]
