# Generated by Django 6.0.1 on 2026-01-28 14:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_routestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='day_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestop',
            name='duration_minutes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestop',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestop',
            name='location_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestop',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='routestop',
            name='type',
            field=models.CharField(choices=[('DRIVE', 'Drive'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('REST', 'Rest'), ('FUEL', 'Fuel'), ('BREAK', 'Break')], default='DRIVE', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('total_driving_hours', models.DurationField()),
                ('total_on_duty_hour', models.DurationField()),
                ('total_off_duty_hour', models.DurationField()),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to='trip.trip')),
            ],
        ),
        migrations.CreateModel(
            name='LogSegment',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OFF', 'Off Duty'), ('SLEEPER', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY', 'On Duty')], max_length=10)),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('daily_log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_segments', to='trip.dailylog')),
            ],
        ),
    ]
