# Generated by Django 6.0.1 on 2026-01-31 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_routestop_day_number_routestop_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsegment',
            old_name='daily_log_id',
            new_name='daily_log',
        ),
        migrations.RenameField(
            model_name='routestop',
            old_name='trip_id',
            new_name='trip',
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='logsegment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='type',
            field=models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('FUEL', 'Fuel')], max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='cycle_used_hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trip',
            name='total_duration_hours',
            field=models.FloatField(),
        ),
    ]
