# Generated by Django 6.0.1 on 2026-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_rename_daily_log_id_logsegment_daily_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestop',
            name='type',
            field=models.CharField(choices=[('DRIVING', 'Driving'), ('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff'), ('REST', 'Rest'), ('FUEL', 'Fuel'), ('BREAK', 'Break')], max_length=10),
        ),
    ]
